### ISSUE TITLE
Impossible de commander 10 plats.

### ISSUE THREAD

**Issue by EricPintea** [Benjozork/TP1-AssuranceQualit-#2]
Comportement attedu:
 Les clients peuvent commander jusqu'au 10 plats.

     Comportement réel:
Le nombre maximum des plats qui peut être demandé est 9. 
[facture_output.txt](https://github.com/Benjozork/TP1-AssuranceQualit-/files/4512475/facture_output.txt)

**Comment by EricPintea** [comment]
Je n'arrive pas a trouver l'erreur dans mon code.

**Comment by Benjozork** [comment]
Le problème se situe à cette ligne : 

```java
if (this.quantite >= MAX_QUANTITE_PLATS) {
    this.erreurDansQuantite = "Quantité en haut de 10";
}
```

Il faut changer le `>=` en `>`.

**Comment by Benjozork** [comment]
Le problème se situe à cette ligne :

if (this.quantite >= MAX_QUANTITE_PLATS) {
    this.erreurDansQuantite = "Quantité en haut de 10";
}

Il faut changer le >= en >.

**Comment by EricPintea** [comment]
merci
