### ISSUE TITLE
Un client avec un total de 0 s'affiche quand même dans le grand total

### ISSUE THREAD

**Issue by Louis-M8** [Benjozork/TP1-AssuranceQualit-#3]
## Comportement attendu

un client avec un total de 0 ne devraiet pas appraitre dans la liste

## Comportement réel

le client n'apparait pas dans les sections clients mais apparait dans le grand total

![image](https://user-images.githubusercontent.com/60261194/79924024-cfd80d80-8404-11ea-9d25-25dc785cae25.png)

**Comment by Benjozork** [comment]
Reproduit en date du commit c68eb1cf
